### ISSUE TITLE
Merge the undocumented and documented notebooks

### ISSUE THREAD

**Issue by benbowen** [benbowen/Model_Time_Series_Data#1]
After merging the notesbooks remove the unnecessary one.

**Comment by oerbilgin** [comment]
done. Merged notebook names:
- `Fit Time Series Metabolomics Data, verbose`, which has all the documentation but no functions. I'll make a new notebook with all the new functions (fitting, plotting, etc)
- `Load and Pickle Time Series Metabolomics Data`
  The `Onur's Sandbox` notebook is where I run practice code to see how things work (mainly pandas)

**Comment by oerbilgin** [comment]
But I forgot how to use git :(
